//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
use schemars::JsonSchema;
use sea_orm::{ActiveValue::{NotSet, Set}, EntityOrSelect, ExprTrait, FromQueryResult, QuerySelect, entity::prelude::*, sea_query::{Alias, Func, Mode}};
use serde::{Deserialize, Serialize};
use crate::{backenddb::{entrys::example_game, game::{self, AvgReturn, GamesAvgSpecific, GamesEditSpecific, GamesFull, GamesFullSpecific, GamesGraph, GamesGraphSpecific, GamesInserts, GamesInsertsSpecific, InsertReturn, NormalSpcDataAvg, TeamAvg, TeamGameUnMergedData, YearOp}}, entity::genertic_header};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, JsonSchema)]
#[sea_orm(table_name = "example_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    pub hehe: i32,
    pub beep: i32,
    pub hoohoo: String,
}

pub const YEAR: i32 = 9999;


fn get_total_score(hehe: i32, beep: i32) -> i32 {
        hehe * 6 + beep * 7
}

fn get_auto_score(hehe: i32, beep: i32) -> i32 {
    hehe * 6
}

fn get_teleop_score(hehe: i32, beep: i32) -> i32 {
    beep * 7
}

pub struct Functions;

//                                                             Game Type ID>↓.     ↓<Game Id

#[async_trait]
impl YearOp for Functions {
    fn get_year_id(&self) -> i32 {
        YEAR
    }

    async fn insert(&self, data: &GamesInsertsSpecific, db: &DatabaseConnection) -> Result<InsertReturn, DbErr> {
        match &data {
            GamesInsertsSpecific::ExampleGame(a) => {
                let game_db: ActiveModel = ActiveModel { 
                    id: NotSet, 
                    hehe: Set(a.hehe), 
                    beep: Set(a.beep), 
                    hoohoo: Set(a.hoohoo.clone())
                };
                let res = InsertReturn {
                    game_type: self.get_year_id(),
                    game_id: Entity::insert(game_db).exec(db).await?.last_insert_id,
                    total_score: get_total_score(a.hehe, a.beep),
                    teleop_score: get_teleop_score(a.hehe, a.beep),
                    auto_score: get_auto_score(a.hehe, a.beep)
                };
                return Ok(res);
            },
            _ => {
                Err(DbErr::AttrNotSet("This is invaild type for the current year!".to_string()))
            }
        }
    }
    async fn average_team(&self, ids: Vec<TeamGameUnMergedData>, db: &DatabaseConnection) -> Result<Vec<AvgReturn>, DbErr> {
        let mut returns: Vec<AvgReturn> = Vec::with_capacity(ids.len());
        for team in ids {
            if team.game_ids.is_empty() {
                continue;
            }
            let team_avg_data = example_game::Entity::find()
                .filter(example_game::Column::Id.is_in(team.game_ids))
                .select_only()
                .column_as(example_game::Column::Hehe.avg().cast_as(Alias::new("FLOAT8")), "hehe_avg")
                .column_as(example_game::Column::Beep.avg().cast_as(Alias::new("FLOAT8")), "beep_avg")
                .into_model::<Avg>()
                .one(db).await?.ok_or(DbErr::Custom(format!("Could not find data for team {}", team.team)))?;
            returns.push(AvgReturn { team: team.team, is_ab_team: team.is_ab_team, data: GamesAvgSpecific::ExampleGame(team_avg_data) });
        }

        return Ok(returns);
    }


    async fn get_full_matches(&self, game_ids: Vec<i32>, db: &DatabaseConnection) -> Result<Vec<game::GamesFullSpecific>, DbErr> {
        match Entity::find()
            .filter(Column::Id.is_in(game_ids.clone()))
            .all(db).await {
                Ok(mut a) => {
                    a.sort_by_key(|entry| {
                        game_ids.iter().position(|id| *id == entry.id).unwrap_or(usize::MAX)
                    });
                    Ok(a.into_iter().map(|x| {
                        GamesFullSpecific::ExampleGame(x)
                    }).collect())
                },
                Err(a) => {Err(a)},
            }
    }
    
    async fn delete(&self, id: i32, db: &DatabaseConnection) -> Result<(), DbErr> {
        Entity::delete_by_id(id).exec(db).await?;

        Ok(())
    }
    
    async fn get(&self, id: i32, db: &DatabaseConnection) -> Result<GamesFullSpecific, DbErr> {
        let res = Entity::find_by_id(id).one(db).await?;
        match res {
            Some(a) => Ok(GamesFullSpecific::ExampleGame(a)),
            None => Err(DbErr::RecordNotFound("Could not find".to_string())),
        }
    }
    
    async fn edit(&self, mut header: genertic_header::ActiveModel, edit: GamesEditSpecific, db: &DatabaseConnection) -> Result<(), DbErr> {
        //get total score
        //We unwrap as if called from the correct funcsion game_id should be set
        let id_to_unfuck_rust = header.game_id.clone();
        let total_score = Entity::find_by_id(id_to_unfuck_rust.unwrap()).one(db).await?.ok_or(DbErr::RecordNotFound("Could not find game data to edit!".to_string()))?;
        
        let am = match edit {
            GamesEditSpecific::ExampleGame(a) => {
                let hehe = a.hehe.unwrap_or(total_score.hehe);
                let beep = a.beep.unwrap_or(total_score.beep);
                let score = get_total_score(hehe, beep);
                let auto_score = get_auto_score(hehe, beep);
                let teleop_score = get_teleop_score(hehe, beep);
                header.total_score = Set(score);
                header.auto_score = Set(auto_score);
                header.teleop_score = Set(teleop_score);
                let header_data = header.update(db).await?;

                ActiveModel {
                    id: Set(header_data.game_id), 
                    hehe: a.hehe.map(Set).unwrap_or(NotSet),
                    beep: a.beep.map(Set).unwrap_or(NotSet),
                    hoohoo: a.hoohoo.map(Set).unwrap_or(NotSet)
                }
            }
            _ => {
                return Err(DbErr::AttrNotSet("Wrong game!".to_string()));
            }
        };

        let res = am.update(db).await?;

        Ok(())
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

//Structures for sending between

#[derive(Serialize, JsonSchema, Deserialize)]
pub struct Insert {
    pub hehe: i32,
    pub beep: i32,
    pub hoohoo: String
}

#[derive(Serialize, JsonSchema, Deserialize)]
pub struct Edit {
    pub hehe: Option<i32>,
    pub beep: Option<i32>,
    pub hoohoo: Option<String>
}


#[derive(Serialize, JsonSchema)]
pub struct Graph {
    //Per game
    pub hehe: i32,
    pub beep: i32,
}



#[derive(Serialize, JsonSchema, FromQueryResult)]
pub struct Avg {
    pub hehe_avg: f64,
    pub beep_avg: f64,
}