//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
use std::collections::{HashMap, HashSet};

use schemars::{JsonSchema};
use sea_orm::{ActiveValue::{NotSet, Set, Unchanged}, ExprTrait, FromQueryResult, IntoSimpleExpr, QuerySelect, entity::prelude::*, sea_query::Alias};
use serde::{Deserialize, Serialize};
use crate::{backenddb::{frontrunnner::find_disagreeing_indexes, game::{self, AvgReturn, FrontRunnerReturn, GamesAvgSpecific, GamesEditSpecific, GamesFullSpecific, GamesInsertsSpecific, InsertReturn, TeamGameUnMergedData, YearOp}}, entity::genertic_header, frontend::pit::insert::insert, snowgrave::find_point_distance::check_pass};
use std::hash::Hash;

const FUEL_TELEOP: f32 = 1.0;
const FUEL_AUTO: f32 = 1.0;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    JsonSchema,
    Hash,
Copy
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "climb_state")]
pub enum ClimbState {
    #[sea_orm(string_value = "nothing")]
    Nothing,

    #[sea_orm(string_value = "stage1")]
    Stage1,

    #[sea_orm(string_value = "stage2")]
    Stage2,

    #[sea_orm(string_value = "stage3")]
    Stage3,
}

const STAGE_1_TELEOP: i32 = 10;
const STAGE_2_TELEOP: i32 = 20;
const STAGE_3_TELEOP: i32 = 30;
const STAGE_1_AUTO: i32 = 15;
const STAGE_2_AUTO: i32 = 15;
const STAGE_3_AUTO: i32 = 15;


#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, JsonSchema)]
#[sea_orm(table_name = "rebuilt_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    pub defence_main: bool, // X S
    pub fuel_shoot_teleop: f32,
    pub fuel_pass_teleop: f32,
    pub fuel_shoot_auto: f32,
    pub fuel_pass_auto: f32,
    pub climb_end: ClimbState, //X S
    pub climb_auto: ClimbState, // X S
    pub beach_on_bump: bool, //X 
}

pub struct FrontRunner {
    crazy: Vec<usize>,
    avg: ActiveModel
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


pub const YEAR: i32 = 2026;

//impl
pub struct Functions;



macro_rules! enum_pct {
    ($column:expr, $variant:expr) => {
        Expr::col($column)
            .eq($variant)
            .into_simple_expr()
            .cast_as(Alias::new("INT"))
            .avg()
            .cast_as(Alias::new("FLOAT8"))
    };
}

fn total_score_auto(insert_data: &Insert) -> f32 {
    let fuel_auto = insert_data.fuel_shoot_auto * FUEL_AUTO;
    

    let climb_score: i32;
    match insert_data.climb_auto {
        ClimbState::Stage1 => {
            climb_score = STAGE_1_AUTO;
        },
        ClimbState::Stage2 => {
            climb_score = STAGE_2_AUTO;
        },
        ClimbState::Stage3 => {
            climb_score = STAGE_3_AUTO;
        },
        ClimbState::Nothing => {
            climb_score = 0;
        },
    }

    climb_score as f32 + fuel_auto
}

fn total_score_teleop(insert_data: &Insert) -> f32 {
    let fuel_teleop = insert_data.fuel_shoot_teleop * FUEL_TELEOP;

    let climb_score: i32;
    match insert_data.climb_end {
        ClimbState::Stage1 => {
            climb_score = STAGE_1_TELEOP;
        },
        ClimbState::Stage2 => {
            climb_score = STAGE_2_TELEOP;
        },
        ClimbState::Stage3 => {
            climb_score = STAGE_3_TELEOP;
        },
        ClimbState::Nothing => {
            climb_score = 0;
        },
    }

    climb_score as f32 + fuel_teleop
}

#[async_trait]
impl YearOp for Functions {
    fn get_year_id(&self) -> i32 {
        YEAR
    }

    fn frontrunner_op(&self, games: Vec<GamesFullSpecific>) -> Result<FrontRunnerReturn, DbErr> {
        //check right year
        let models: Vec<Model> = games.into_iter().map(|x| {
            match x {
                GamesFullSpecific::RebuiltGame(model) => {
                    model
                },
                _ => {
                    panic!("Invalid year!");
                }
            }
        }).collect();

        //first, we check what values HAVE to agree or else we are fully wack
        let mut crazy: HashSet<usize> = HashSet::new();
        let mut avg: ActiveModel = ActiveModel {..Default::default()};


        //check if defence is sane
        let defences: Vec<bool> = models.iter().map(|x| x.defence_main.clone()).collect();
        let mode = find_disagreeing_indexes(&defences);
        if let Some(mode_safe) = mode {
            crazy.extend(mode_safe.1);
            avg.defence_main = Set(mode_safe.0)
        } else {
            //array is not full, we need to error
            return Err(DbErr::Custom("[FRONTRUNNER][REBUILT][CHECK] Array is not full!".to_string()));
        }

        //check if climb_end is the same
        let climb_ends: Vec<ClimbState> = models.iter().map(|x| x.climb_end.clone()).collect();
        let mode = find_disagreeing_indexes(&climb_ends);
        if let Some(mode_safe) = mode {
            crazy.extend(mode_safe.1);
            avg.climb_end = Set(mode_safe.0)
        } else {
            //array is not full, we need to error
            return Err(DbErr::Custom("[FRONTRUNNER][REBUILT][CHECK] Array is not full!".to_string()));
        }

        let climb_auto: Vec<ClimbState> = models.iter().map(|x| x.climb_auto.clone()).collect();
        let mode = find_disagreeing_indexes(&climb_auto);
        if let Some(mode_safe) = mode {
            crazy.extend(mode_safe.1);
            avg.climb_auto = Set(mode_safe.0)
        } else {
            //array is not full, we need to error
            return Err(DbErr::Custom("[FRONTRUNNER][REBUILT][CHECK] Array is not full!".to_string()));
        }

        let beach_on_bump: Vec<bool> = models.iter().map(|x| x.beach_on_bump.clone()).collect();
        let mode = find_disagreeing_indexes(&beach_on_bump);
        if let Some(mode_safe) = mode {
            crazy.extend(mode_safe.1);
            avg.beach_on_bump = Set(mode_safe.0)
        } else {
            //array is not full, we need to error
            return Err(DbErr::Custom("[FRONTRUNNER][REBUILT][CHECK] Array is not full!".to_string()));
        }


        //check indexes for fuel
        let fuel_shoot_teleops: Vec<f32> = models.iter().map(|x| x.fuel_shoot_teleop).collect();
        let fuel_res = check_pass(&fuel_shoot_teleops);
        crazy.extend(fuel_res.failed);
        let mut total: f32 = 0.0;
        for amount in &fuel_res.passed {
            total += fuel_shoot_teleops[*amount];
        }
        avg.fuel_shoot_teleop = Set(total/fuel_res.passed.len() as f32);

        let fuel_pass_teleops: Vec<f32> = models.iter().map(|x| x.fuel_pass_teleop).collect();
        let fuel_res = check_pass(&fuel_pass_teleops);
        crazy.extend(fuel_res.failed);
        let mut total: f32 = 0.0;
        for amount in &fuel_res.passed {
            total += &fuel_pass_teleops[*amount];
        }
        avg.fuel_pass_teleop = Set(total/fuel_res.passed.len() as f32);

        let fuel_shoot_autos: Vec<f32> = models.iter().map(|x| x.fuel_shoot_auto).collect();
        let fuel_res = check_pass(&fuel_shoot_autos);
        crazy.extend(fuel_res.failed);
        let mut total: f32 = 0.0;
        for amount in &fuel_res.passed {
            total += &fuel_shoot_autos[*amount];
        }
        avg.fuel_shoot_auto = Set(total/fuel_res.passed.len() as f32);

        let fuel_pass_autos: Vec<f32> = models.iter().map(|x| x.fuel_pass_auto).collect();
        let fuel_res = check_pass(&fuel_pass_autos);
        crazy.extend(fuel_res.failed);
        let mut total: f32 = 0.0;
        for amount in &fuel_res.passed {
            total += fuel_pass_autos[*amount];
        }
        avg.fuel_pass_auto = Set(total/fuel_res.passed.len() as f32);
        

        let crazy_fixed: Vec<usize> = crazy.into_iter().collect();

        Ok(FrontRunnerReturn::RebuiltGame(FrontRunner {
            crazy: crazy_fixed,
            avg,
        }))
    }

    async fn insert(&self, data: &GamesInsertsSpecific, db: &DatabaseConnection) -> Result<InsertReturn, DbErr> {
        match data {
            GamesInsertsSpecific::RebuiltGame(insert) => {
                //convert the types to a achive model
                let active = ActiveModel {
                    id: NotSet,
                    defence_main: Set(insert.defence_main),
                    fuel_shoot_teleop: Set(insert.fuel_shoot_teleop),
                    fuel_pass_teleop: Set(insert.fuel_pass_teleop),
                    fuel_shoot_auto: Set(insert.fuel_shoot_auto),
                    fuel_pass_auto: Set(insert.fuel_pass_auto),
                    climb_end: Set(insert.climb_end),
                    climb_auto: Set(insert.climb_auto),
                    beach_on_bump: Set(insert.beach_on_bump)
                };
                let res = Entity::insert(active).exec(db).await?;
                let auto_score = total_score_auto(insert);
                let teleop_score = total_score_teleop(insert);
                let total_score = auto_score + teleop_score;


                Ok(InsertReturn {
                    game_type: self.get_year_id(),
                    game_id: res.last_insert_id,
                    total_score,
                    teleop_score,
                    auto_score
                })
            },
            _ => {
                return Err(DbErr::Custom("Invaild year in insert!".to_string()));
            }
        }
    }
    async fn average_team(&self, ids: Vec<TeamGameUnMergedData>, db: &DatabaseConnection) -> Result<Vec<AvgReturn>, DbErr> {
        let mut returns: Vec<AvgReturn> = Vec::with_capacity(ids.len());
        for team in ids {
            if team.game_ids.is_empty() {
                continue;
            }
            let team_avg_data = Entity::find()
                .filter(Column::Id.is_in(team.game_ids))
                .select_only()
                .column_as(Column::FuelShootTeleop.avg().cast_as(Alias::new("FLOAT8")), "fuel_shoot_teleop_avg")
                .column_as(Column::FuelPassTeleop.avg().cast_as(Alias::new("FLOAT8")), "fuel_pass_teleop_avg")
                .column_as(Column::FuelShootAuto.avg().cast_as(Alias::new("FLOAT8")), "fuel_shoot_auto_avg")
                .column_as(Column::FuelPassAuto.avg().cast_as(Alias::new("FLOAT8")), "fuel_pass_auto_avg")
                .column_as(Column::BeachOnBump.avg().cast_as(Alias::new("FLOAT8")), "beach_on_bump")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage1
                ), "level_1_avg")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage2
                ), "level_2_avg")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage3
                ), "level_3_avg")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage1
                ), "level_1_avg_auto")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage2
                ), "level_2_avg_auto")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage3
                ),"level_3_avg_auto")
                .into_model::<Avg>()
                .one(db).await?.ok_or(DbErr::Custom(format!("Could not find data for team {}", team.team)))?;
            returns.push(AvgReturn { team: team.team, is_ab_team: team.is_ab_team, data: GamesAvgSpecific::RebuiltGame(team_avg_data) });
        }

        return Ok(returns);
    }


    async fn get_full_matches(&self, game_ids: Vec<i32>, db: &DatabaseConnection) -> Result<Vec<game::GamesFullSpecific>, DbErr> {
        match Entity::find()
            .filter(Column::Id.is_in(game_ids.clone()))
            .all(db)
            .await
        {
            Ok(mut a) => {
                a.sort_by_key(|entry| {
                    game_ids.iter()
                        .position(|id| *id == entry.id)
                        .unwrap_or(usize::MAX)
                });

                Ok(a.into_iter()
                    .map(GamesFullSpecific::RebuiltGame)
                    .collect())
            }
            Err(a) => Err(a),
        }
    }
    
    async fn delete(&self, id: i32, db: &DatabaseConnection) -> Result<(), DbErr> {
        let res = Entity::delete_by_id(id).exec(db).await?;
        Ok(())
    }
    
    async fn get(&self, id: i32, db: &DatabaseConnection) -> Result<GamesFullSpecific, DbErr> {
        match Entity::find_by_id(id).one(db).await? {
            None => {
                Err(DbErr::Custom("This ID is invaild!".to_string()))
            }
            Some(x) => {
                Ok(GamesFullSpecific::RebuiltGame(x))
            }
        }
    }
    
    async fn edit(&self, mut header: genertic_header::ActiveModel, edit: GamesEditSpecific, db: &DatabaseConnection) -> Result<(), DbErr> {
        let game_id = match header.game_id {
            Set(x) => {
                x
            },
            Unchanged(x) => {
                x
            }
            NotSet => {
                return Err(DbErr::Custom("Did not init the id tag for the game!".to_string()));
            }
        };

        let game_model = match Entity::find_by_id(game_id).one(db).await? {
            None => {
                return Err(DbErr::Custom("Could not find model (invaild game id)".to_string()));
            },
            Some(a) => {
                a
            }
        };

        match edit {
            GamesEditSpecific::RebuiltGame(edit) => {
                let total_score = Insert {
                    defence_main: edit.defence_main.unwrap_or(game_model.defence_main),
                    fuel_shoot_teleop: edit.fuel_shoot_teleop.unwrap_or(game_model.fuel_shoot_teleop),
                    fuel_pass_teleop: edit.fuel_pass_teleop.unwrap_or(game_model.fuel_pass_teleop),
                    fuel_shoot_auto: edit.fuel_shoot_auto.unwrap_or(game_model.fuel_shoot_auto),
                    fuel_pass_auto: edit.fuel_pass_auto.unwrap_or(game_model.fuel_pass_auto),
                    climb_end: edit.climb_end.unwrap_or(game_model.climb_end),
                    climb_auto: edit.climb_auto.unwrap_or(game_model.climb_auto),
                    beach_on_bump: edit.beach_on_bump.unwrap_or(game_model.beach_on_bump)
                };
                header.auto_score = Set(total_score_auto(&total_score));
                header.teleop_score = Set(total_score_teleop(&total_score));
                header.total_score = Set(total_score_auto(&total_score) + total_score_teleop(&total_score));

                let header_data = header.update(db).await?;
                let game_data_active = ActiveModel {id:Set(game_id),defence_main:Set(total_score.defence_main),fuel_shoot_teleop:Set(total_score.fuel_shoot_teleop),fuel_pass_teleop:Set(total_score.fuel_pass_teleop),fuel_shoot_auto:Set(total_score.fuel_shoot_auto),fuel_pass_auto:Set(total_score.fuel_pass_auto),climb_end:Set(total_score.climb_end),climb_auto:Set(total_score.climb_auto), beach_on_bump: todo!() };
                let game_data = game_data_active.update(db).await?;
                Ok(())
            },
            _ => {
                return Err(DbErr::Custom("Invaild year!".to_string()));
            }
        }
    }
}



#[derive(Serialize, JsonSchema, Deserialize)]
pub struct Insert {
    pub defence_main: bool,
    pub fuel_shoot_teleop: f32,
    pub fuel_pass_teleop: f32,
    pub fuel_shoot_auto: f32,
    pub fuel_pass_auto: f32,
    pub climb_end: ClimbState,
    pub climb_auto: ClimbState,
    pub beach_on_bump: bool,
}

#[derive(Serialize, JsonSchema, Deserialize)]
pub struct Edit {
    pub defence_main: Option<bool>,
    pub fuel_shoot_teleop: Option<f32>,
    pub fuel_pass_teleop: Option<f32>,
    pub fuel_shoot_auto: Option<f32>,
    pub fuel_pass_auto: Option<f32>,
    pub climb_end: Option<ClimbState>,
    pub climb_auto: Option<ClimbState>,
    pub beach_on_bump: Option<bool>,
}

#[derive(Serialize, JsonSchema, FromQueryResult)]
pub struct Avg {
    pub defence_main_avg: f64,
    pub fuel_shoot_teleop_avg: f64,
    pub fuel_pass_teleop_avg: f64,
    pub fuel_shoot_auto_avg: f64,
    pub fuel_pass_auto_avg: f64,
    pub level_1_avg: f64,
    pub level_2_avg: f64,
    pub level_3_avg: f64,
    pub level_1_avg_auto: f64,
    pub level_2_avg_auto: f64,
    pub level_3_avg_auto: f64,
    pub beach_on_bump: f64
}