//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17
use std::collections::{HashMap, HashSet};

use schemars::{JsonSchema};
use sea_orm::{ActiveValue::{NotSet, Set, Unchanged}, ExprTrait, FromQueryResult, IntoSimpleExpr, QuerySelect, entity::prelude::*, sea_query::Alias};
use serde::{Deserialize, Serialize};
use crate::{backenddb::{frontrunnner::{average_field, consensus_field, find_disagreeing_indexes}, game::{self, AvgReturn, FrontRunnerGame, FrontRunnerReturn, GamesAvgSpecific, GamesEditSpecific, GamesFull, GamesFullSpecific, GamesInserts, GamesInsertsSpecific, HeaderInsert, InsertReturn, Scores, TeamGameUnMergedData, YearOp}}, entity::genertic_header, frontend::pit::insert::insert, snowgrave::find_point_distance::check_pass};
use std::hash::Hash;

const FUEL_TELEOP: f32 = 1.0;
const FUEL_AUTO: f32 = 1.0;

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    JsonSchema,
    Hash,
    Copy,
    Default
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "climb_state")]
pub enum ClimbState {
    #[default]
    #[sea_orm(string_value = "nothing")]
    Nothing,

    #[sea_orm(string_value = "stage1")]
    Stage1,

    #[sea_orm(string_value = "stage2")]
    Stage2,

    #[sea_orm(string_value = "stage3")]
    Stage3,
}

const STAGE_1_TELEOP: i32 = 10;
const STAGE_2_TELEOP: i32 = 20;
const STAGE_3_TELEOP: i32 = 30;
const STAGE_1_AUTO: i32 = 15;
const STAGE_2_AUTO: i32 = 15;
const STAGE_3_AUTO: i32 = 15;


#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, JsonSchema, Default)]
#[sea_orm(table_name = "rebuilt_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    pub defence_main: bool, // X S
    pub fuel_shoot_teleop: f32,
    pub fuel_pass_teleop: f32,
    pub fuel_shoot_auto: f32,
    pub fuel_pass_auto: f32,
    pub climb_end: ClimbState, //X S
    pub climb_auto: ClimbState, // X S
    pub beach_on_bump: bool, //X 
    pub dead: bool,
    pub dnf: bool,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


pub const YEAR: i32 = 2026;

//impl
pub struct Functions;



macro_rules! enum_pct {
    ($column:expr, $variant:expr) => {
        Expr::case(
            Expr::col($column).eq(
                Expr::val($variant.clone().into_value())
                    .cast_as(Alias::new("climb_state")) // 👈 key fix
            ),
            Expr::val(1)
        )
        .finally(Expr::val(0))
        .avg()
        .cast_as(Alias::new("FLOAT8"))
    };
}


fn total_score_auto(insert_data: &Insert) -> f32 {
    let fuel_auto = insert_data.fuel_shoot_auto * FUEL_AUTO;
    

    let climb_score: i32;
    match insert_data.climb_auto {
        ClimbState::Stage1 => {
            climb_score = STAGE_1_AUTO;
        },
        ClimbState::Stage2 => {
            climb_score = STAGE_2_AUTO;
        },
        ClimbState::Stage3 => {
            climb_score = STAGE_3_AUTO;
        },
        ClimbState::Nothing => {
            climb_score = 0;
        },
    }

    climb_score as f32 + fuel_auto
}

fn total_score_teleop(insert_data: &Insert) -> f32 {
    let fuel_teleop = insert_data.fuel_shoot_teleop * FUEL_TELEOP;

    let climb_score: i32;
    match insert_data.climb_end {
        ClimbState::Stage1 => {
            climb_score = STAGE_1_TELEOP;
        },
        ClimbState::Stage2 => {
            climb_score = STAGE_2_TELEOP;
        },
        ClimbState::Stage3 => {
            climb_score = STAGE_3_TELEOP;
        },
        ClimbState::Nothing => {
            climb_score = 0;
        },
    }

    climb_score as f32 + fuel_teleop
}

#[async_trait]
impl YearOp for Functions {
    fn get_scores(&self, game: &GamesInsertsSpecific) -> Scores {
        match &game {
            &GamesInsertsSpecific::RebuiltGame(model) => {
                let teleop_score = total_score_teleop(&model);
                let auto_score = total_score_auto(&model);
                Scores {
                    total_score: teleop_score + auto_score,
                    teleop_score,
                    auto_score
                }
            },
            _ => {
                panic!("Wrong year!");
            }
        }
    }

    fn get_year_id(&self) -> i32 {
        YEAR
    }
    fn frontrunner_op(
        &self,
        games: &FrontRunnerGame,
    ) -> Result<FrontRunnerReturn, DbErr> {

        let models: Vec<&Model> = games.games
            .iter()
            .map(|x| match &x.1 {
                GamesFullSpecific::RebuiltGame(model) => model,
                _ => panic!("Invalid year!"),
            })
            .collect();

        let mut crazy: HashSet<usize> = HashSet::new();
        let mut avg = Insert::default();

        // Consensus fields
        avg.defence_main = match consensus_field(&models, &mut crazy, |m| m.defence_main, "defence_main") {
            Some(a) => a,
            None => {
                //get all crasy
                crazy.extend(0..models.len() as usize);

                return Ok(FrontRunnerReturn {
                    crazy: crazy.into_iter().collect(),
                    avg: None,
                });
            },
        };

        avg.climb_end = match consensus_field(&models, &mut crazy, |m| m.climb_end, "climb_end") {
            Some(a) => a,
            None => {
                crazy.extend(0..models.len());
                return Ok(FrontRunnerReturn { crazy: crazy.into_iter().collect(), avg: None });
            },
        };

        avg.climb_auto = match consensus_field(&models, &mut crazy, |m| m.climb_auto, "climb_auto") {
            Some(a) => a,
            None => {
                crazy.extend(0..models.len());
                return Ok(FrontRunnerReturn { crazy: crazy.into_iter().collect(), avg: None });
            },
        };

        avg.beach_on_bump = match consensus_field(&models, &mut crazy, |m| m.beach_on_bump, "beach_on_bump") {
            Some(a) => a,
            None => {
                crazy.extend(0..models.len());
                return Ok(FrontRunnerReturn { crazy: crazy.into_iter().collect(), avg: None });
            },
        };

        avg.dead = match consensus_field(&models, &mut crazy, |m| m.dead, "dead") {
            Some(a) => a,
            None => {
                crazy.extend(0..models.len());
                return Ok(FrontRunnerReturn { crazy: crazy.into_iter().collect(), avg: None });
            },
        };

        avg.dnf = match consensus_field(&models, &mut crazy, |m| m.dnf, "dnf") {
            Some(a) => a,
            None => {
                crazy.extend(0..models.len());
                return Ok(FrontRunnerReturn { crazy: crazy.into_iter().collect(), avg: None });
            },
        };

        // Numeric fields
        avg.fuel_shoot_teleop =
            average_field(&models, &mut crazy, |m| m.fuel_shoot_teleop, "fuel_shoot_teleop")?;

        avg.fuel_pass_teleop =
            average_field(&models, &mut crazy, |m| m.fuel_pass_teleop, "fuel_pass_teleop")?;

        avg.fuel_shoot_auto =
            average_field(&models, &mut crazy, |m| m.fuel_shoot_auto, "fuel_shoot_auto")?;

        avg.fuel_pass_auto =
            average_field(&models, &mut crazy, |m| m.fuel_pass_auto, "fuel_pass_auto")?;

        let mut users: Vec<Uuid> = Vec::new(); 
        for user in games.games.iter().enumerate() {
            if !crazy.contains(&user.0) {
                users.push(user.1.0.clone());
            }
        }
        let mut sum: f32 = 0.0;
        let mut amount: i32 = 0;
        for defence_one in games.defence.iter().enumerate() {
            if !crazy.contains(&defence_one.0) {
                sum += defence_one.1;
                amount += 1;
            }
        }
        let defence = sum / (amount as f32);
        
        let comment = games.comment
            .iter()
            .enumerate()
            .filter_map(|(i, c)| {
                if !crazy.contains(&i) {
                    Some(c)
                } else {
                    None
                }
            })
            .max_by_key(|c| c.len())
            .cloned()
            .unwrap_or_default();
                        
        let header = HeaderInsert {
            user: users,
            team: games.team,
            is_ab_team: games.is_ab_team,
            match_id: games.match_id,
            set: games.set,
            defence: defence,
            event_code: games.event_code.clone(),
            tournament_level: games.tournament_level,
            station: games.station,
            is_mvp: games.is_mvp,
            comment: comment
        };

        Ok(FrontRunnerReturn {
            crazy: crazy.into_iter().collect(),
            avg: Some(GamesInserts { 
                header,
                game: GamesInsertsSpecific::RebuiltGame(avg) 
            }),
        })
    }

    async fn insert(&self, data: &GamesInsertsSpecific, db: &DatabaseConnection) -> Result<InsertReturn, DbErr> {
        match data {
            GamesInsertsSpecific::RebuiltGame(insert) => {
                //convert the types to a achive model
                let active = ActiveModel {
                    id: NotSet,
                    defence_main: Set(insert.defence_main),
                    fuel_shoot_teleop: Set(insert.fuel_shoot_teleop),
                    fuel_pass_teleop: Set(insert.fuel_pass_teleop),
                    fuel_shoot_auto: Set(insert.fuel_shoot_auto),
                    fuel_pass_auto: Set(insert.fuel_pass_auto),
                    climb_end: Set(insert.climb_end),
                    climb_auto: Set(insert.climb_auto),
                    beach_on_bump: Set(insert.beach_on_bump),
                    dead: Set(insert.dead),
                    dnf: Set(insert.dnf)
                };
                let res = Entity::insert(active).exec(db).await?;
                let auto_score = total_score_auto(insert);
                let teleop_score = total_score_teleop(insert);
                let total_score = auto_score + teleop_score;


                Ok(InsertReturn {
                    game_type: self.get_year_id(),
                    game_id: res.last_insert_id,
                    total_score,
                    teleop_score,
                    auto_score
                })
            },
            _ => {
                return Err(DbErr::Custom("Invaild year in insert!".to_string()));
            }
        }
    }
    async fn average_team(&self, ids: Vec<TeamGameUnMergedData>, db: &DatabaseConnection) -> Result<Vec<AvgReturn>, DbErr> {
        let mut returns: Vec<AvgReturn> = Vec::with_capacity(ids.len());
        for team in ids {
            if team.game_ids.is_empty() {
                continue;
            }
            let team_avg_data = Entity::find()
                .filter(Column::Id.is_in(team.game_ids))
                .select_only()
                .column_as(Column::FuelShootTeleop.avg().cast_as(Alias::new("FLOAT8")), "fuel_shoot_teleop_avg")
                .column_as(Column::FuelPassTeleop.avg().cast_as(Alias::new("FLOAT8")), "fuel_pass_teleop_avg")
                .column_as(Column::FuelShootAuto.avg().cast_as(Alias::new("FLOAT8")), "fuel_shoot_auto_avg")
                .column_as(Column::FuelPassAuto.avg().cast_as(Alias::new("FLOAT8")), "fuel_pass_auto_avg")
                .column_as(Expr::col(Column::DefenceMain).cast_as(Alias::new("int")).avg().cast_as(Alias::new("FLOAT8")), "defence_main_avg")
                .column_as(Expr::col(Column::BeachOnBump).cast_as(Alias::new("int")).avg().cast_as(Alias::new("FLOAT8")), "beach_on_bump")
                .column_as(Expr::col(Column::Dead).cast_as(Alias::new("int")).avg().cast_as(Alias::new("FLOAT8")), "dead_avg")
                .column_as(Expr::col(Column::Dnf).cast_as(Alias::new("int")).avg().cast_as(Alias::new("FLOAT8")), "dnf_avg")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage1
                ), "level_1_avg")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage2
                ), "level_2_avg")
                .expr_as(enum_pct!(
                    Column::ClimbEnd,
                    ClimbState::Stage3
                ), "level_3_avg")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage1
                ), "level_1_avg_auto")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage2
                ), "level_2_avg_auto")
                .expr_as(enum_pct!(
                    Column::ClimbAuto,
                    ClimbState::Stage3
                ),"level_3_avg_auto")
                .into_model::<Avg>()
                .one(db).await?.ok_or(DbErr::Custom(format!("Could not find data for team {}", team.team)))?;
            returns.push(AvgReturn { team: team.team, is_ab_team: team.is_ab_team, data: GamesAvgSpecific::RebuiltGame(team_avg_data) });
        }

        return Ok(returns);
    }


    async fn get_full_matches(&self, game_ids: Vec<i32>, db: &DatabaseConnection) -> Result<Vec<game::GamesFullSpecific>, DbErr> {
        match Entity::find()
            .filter(Column::Id.is_in(game_ids.clone()))
            .all(db)
            .await
        {
            Ok(mut a) => {
                a.sort_by_key(|entry| {
                    game_ids.iter()
                        .position(|id| *id == entry.id)
                        .unwrap_or(usize::MAX)
                });

                Ok(a.into_iter()
                    .map(GamesFullSpecific::RebuiltGame)
                    .collect())
            }
            Err(a) => Err(a),
        }
    }
    
    async fn delete(&self, id: i32, db: &DatabaseConnection) -> Result<(), DbErr> {
        let res = Entity::delete_by_id(id).exec(db).await?;
        Ok(())
    }
    
    async fn get(&self, id: i32, db: &DatabaseConnection) -> Result<GamesFullSpecific, DbErr> {
        match Entity::find_by_id(id).one(db).await? {
            None => {
                Err(DbErr::Custom("This ID is invaild!".to_string()))
            }
            Some(x) => {
                Ok(GamesFullSpecific::RebuiltGame(x))
            }
        }
    }
    
    async fn edit(&self, game_id: i32, edit: GamesEditSpecific, db: &DatabaseConnection) -> Result<InsertReturn, DbErr> {

        let game_model = match Entity::find_by_id(game_id).one(db).await? {
            None => {
                return Err(DbErr::Custom("Could not find model (invaild game id)".to_string()));
            },
            Some(a) => {
                a
            }
        };

        match edit {
            GamesEditSpecific::RebuiltGame(edit) => {
                let total_score = Insert {
                    defence_main: edit.defence_main.unwrap_or(game_model.defence_main),
                    fuel_shoot_teleop: edit.fuel_shoot_teleop.unwrap_or(game_model.fuel_shoot_teleop),
                    fuel_pass_teleop: edit.fuel_pass_teleop.unwrap_or(game_model.fuel_pass_teleop),
                    fuel_shoot_auto: edit.fuel_shoot_auto.unwrap_or(game_model.fuel_shoot_auto),
                    fuel_pass_auto: edit.fuel_pass_auto.unwrap_or(game_model.fuel_pass_auto),
                    climb_end: edit.climb_end.unwrap_or(game_model.climb_end),
                    climb_auto: edit.climb_auto.unwrap_or(game_model.climb_auto),
                    beach_on_bump: edit.beach_on_bump.unwrap_or(game_model.beach_on_bump),
                    dead: edit.dead.unwrap_or(game_model.dead),
                    dnf: edit.dnf.unwrap_or(game_model.dnf),
                };

                let returne = InsertReturn {
                    game_type: self.get_year_id(),
                    game_id,
                    total_score: total_score_auto(&total_score) + total_score_teleop(&total_score),
                    teleop_score: total_score_teleop(&total_score),
                    auto_score: total_score_auto(&total_score)
                };
                let game_data_active = ActiveModel {id:Set(game_id),defence_main:Set(total_score.defence_main),fuel_shoot_teleop:Set(total_score.fuel_shoot_teleop),fuel_pass_teleop:Set(total_score.fuel_pass_teleop),fuel_shoot_auto:Set(total_score.fuel_shoot_auto),fuel_pass_auto:Set(total_score.fuel_pass_auto),climb_end:Set(total_score.climb_end),climb_auto:Set(total_score.climb_auto), beach_on_bump: Set(total_score.beach_on_bump), dead: Set(total_score.dead), dnf: Set(total_score.dnf)};
                let game_data = game_data_active.update(db).await?;
                Ok(returne)
            },
            _ => {
                return Err(DbErr::Custom("Invaild year!".to_string()));
            }
        }
    }
}



#[derive(Serialize, JsonSchema, Deserialize, Default, Debug)]
pub struct Insert {
    pub defence_main: bool,
    pub fuel_shoot_teleop: f32,
    pub fuel_pass_teleop: f32,
    pub fuel_shoot_auto: f32,
    pub fuel_pass_auto: f32,
    pub climb_end: ClimbState,
    pub climb_auto: ClimbState,
    pub beach_on_bump: bool,
    pub dead: bool,
    pub dnf: bool,
}

#[derive(Serialize, JsonSchema, Deserialize)]
pub struct Edit {
    pub defence_main: Option<bool>,
    pub fuel_shoot_teleop: Option<f32>,
    pub fuel_pass_teleop: Option<f32>,
    pub fuel_shoot_auto: Option<f32>,
    pub fuel_pass_auto: Option<f32>,
    pub climb_end: Option<ClimbState>,
    pub climb_auto: Option<ClimbState>,
    pub beach_on_bump: Option<bool>,
    pub dead: Option<bool>,
    pub dnf: Option<bool>,
}

#[derive(Serialize, JsonSchema, FromQueryResult)]
pub struct Avg {
    pub defence_main_avg: f64,
    pub fuel_shoot_teleop_avg: f64,
    pub fuel_pass_teleop_avg: f64,
    pub fuel_shoot_auto_avg: f64,
    pub fuel_pass_auto_avg: f64,
    pub dead_avg: f64,
    pub dnf_avg: f64,
    pub level_1_avg: f64,
    pub level_2_avg: f64,
    pub level_3_avg: f64,
    pub level_1_avg_auto: f64,
    pub level_2_avg_auto: f64,
    pub level_3_avg_auto: f64,
    pub beach_on_bump: f64
}