//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::Stations;
use super::sea_orm_active_enums::TournamentLevels;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "genertic_header")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: Uuid,
    pub team: i32,
    pub is_ab_team: bool,
    pub is_mvp: bool,
    pub match_id: i32,
    pub set: i32,
    pub total_score: i32,
    pub event_code: String,
    pub tournament_level: TournamentLevels,
    pub station: Stations,
    pub created_at: DateTime,
    pub is_pending: bool,
    pub is_marked: bool,
    pub snowgrave_scout_id: i32,
    pub game_type_id: i32,
    pub game_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}