//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::Stations;
use super::sea_orm_active_enums::TournamentLevels;
use super::types::DefenceTarget;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "genertic_header")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: Vec<Uuid>,
    pub team: i32,
    pub is_ab_team: bool,
    pub is_mvp: bool,
    pub match_id: i32,
    pub set: i32,
    pub total_score: f32,
    pub teleop_score: f32,
    pub auto_score: f32,
    pub defence: f32,
    pub comment: String,
    pub event_code: String,
    pub tournament_level: TournamentLevels,
    pub station: Stations,
    pub created_at: DateTimeLocal,
    pub game_type_id: i32,
    pub game_id: i32, //not snowgrave
    /// Admin-entered prescout data, which is never mixed with real scouting
    /// data. `NULL` means the row predates this flag, i.e. normal data.
    pub is_prescout: bool,
    pub defence_main: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub defence_target: DefenceTarget,
    pub auto_time: f32,
    pub dead: bool,
    pub dnf: bool,
    pub dpdg: Option<f32>,
    pub dpdg_raw: Option<f32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}