//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pit2025")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: String,
    pub team: i32,
    pub event_code: String,
    pub created_at: DateTime,
    pub height: i32,
    pub width: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
