//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::dyn_settings::Entity as DynSettings;
pub use super::genertic_header::Entity as GenerticHeader;
pub use super::pit2025::Entity as Pit2025;
pub use super::upcoming_game::Entity as UpcomingGame;
pub use super::upcoming_team::Entity as UpcomingTeam;
pub use super::user::Entity as User;
pub use super::users::Entity as Users;
