//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, FromFormField, Serialize, Hash, Copy, Deserialize, JsonSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "stations")]
pub enum Stations {
    #[sea_orm(string_value = "red1")]
    Red1,
    #[sea_orm(string_value = "red2")]
    Red2,
    #[sea_orm(string_value = "red3")]
    Red3,
    #[sea_orm(string_value = "blue1")]
    Blue1,
    #[sea_orm(string_value = "blue2")]
    Blue2,
    #[sea_orm(string_value = "blue3")]
    Blue3,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, FromFormField, Serialize, Copy, Deserialize, JsonSchema)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tournament_levels")]
//TODO: add eight final
pub enum TournamentLevels {
    #[sea_orm(string_value = "qualification_match")]
    QualificationMatch,
    #[sea_orm(string_value = "quarterfinal")]
    Quarterfinal,
    #[sea_orm(string_value = "semifinal")]
    Semifinal,
    #[sea_orm(string_value = "final")]
    Final,
}
