//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::entity::sea_orm_active_enums::{Stations, TournamentLevels};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "upcoming_game")]

pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event_code: String,
    pub match_id: i32,
    pub set: i32,
    pub mvp_id_blue: Option<i32>,
    pub mvp_id_red: Option<i32>,
    pub tournament_level: TournamentLevels,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::upcoming_team::Entity")]
    UpcomingTeam,
}



impl ActiveModelBehavior for ActiveModel {}
