//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user: String,
    pub team: i32,
    pub matchid: i32,
    pub set: i32,
    pub total_score: i32,
    pub event_code: String,
    pub tournament_level: String,
    pub station: String,
    pub created_at: DateTime,
    pub hehe: i32,
    pub hoohoo: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
