//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::dyn_settings::Entity as DynSettings;
pub use super::upcoming_game::Entity as UpcomingGame;
pub use super::upcoming_team::Entity as UpcomingTeam;