//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upcoming_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event_code: String,
    pub match_number: i32,
    pub set_number: i32,
    pub tournament_level: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::upcoming_team::Entity")]
    UpcomingTeam,
}

impl Related<super::upcoming_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UpcomingTeam.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
