//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, Serialize, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upcoming_team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub station: String,
    pub team: i32,
    pub scouter: Option<String>,
    pub game_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::upcoming_game::Entity",
        from = "Column::GameId",
        to = "super::upcoming_game::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UpcomingGame,
}

impl Related<super::upcoming_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UpcomingGame.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
